import { MOCK_PRODUCTS, type Product } from "@/components/storefront/mockData";

export type OrderLineInput = { productId: string; quantity: number };
export type CreateOrderInput = { customerName: string; customerPhone: string; deliveryType: "pickup" | "delivery"; address?: string; slipUrl?: string; items: OrderLineInput[] };
export type OrderStatus = "pending" | "paid" | "fulfilled" | "cancelled";
export type AdminOrder = { id: string; customerName: string; customerPhone: string; createdAt: string; totalAmount: string | number; status: OrderStatus; slipUrl?: string | null; items?: { productId: string; productName?: string | null; quantity: number; pricePerUnit: string | number }[] };
export type ProductWriteInput = { id?: string; name: string; description?: string; category?: string; price: number; unit: string; stock: number; image?: string; isPreOrder?: boolean; harvestDate?: string; researchTag?: string; plotId?: string };
export type ActivityStatus = "draft" | "published" | "scheduled" | "ongoing" | "completed" | "cancelled" | "archived";
export type ActivityWriteInput = { id?: string; projectId?: string; centerId?: string; title: string; slug: string; summary?: string; content?: string; activityDate: string; location?: string; participantCount?: number; objective?: string; process?: string; outcome?: string; impact?: string; featuredImage?: string; status: ActivityStatus };
export type AdminActivity = ActivityWriteInput & { id: string; publishedAt?: string | null; createdAt: string; updatedAt: string };
export type DashboardActivity = { id: string; title: string; activity_date: string; category?: string | null; status: string; participants?: string | number | null; featured_image?: string | null };
export type DashboardOccurrence = { id: string; activity_id: string; occurrence_no: number; start_at: string; end_at?: string | null; status: "draft" | "scheduled" | "ongoing" | "completed" | "cancelled" | "archived"; cancellation_reason?: string | null; participant_count: number; location_type?: string | null; location_detail?: string | null };
export type DashboardLearningCenter = { id: string; name: string; slug: string; type: string; status: string };
export type DashboardOrganization = { id: string; name: string; organization_type: "internal" | "external"; parent_organization_id?: string | null; status: string; display_order: number };
export type DashboardSurvey = { id: string; occurrence_id: string; enabled: boolean; anonymous: boolean; open_at?: string | null; close_at?: string | null; welcome_text?: string | null };
export type DashboardResponse = { id: string; activity_id: string; occurrence_id?: string | null; survey_id?: string | null; participant_organization_id?: string | null; submitted_at: string; age_group?: string | null; affiliation?: string | null; p2_location?: number | null; p2_schedule?: number | null; p2_readiness?: number | null; p2_reception?: number | null; p2_overall?: number | null; p3_interest?: number | null; p3_content?: number | null; p3_clarity?: number | null; p3_benefit?: number | null; p3_application?: number | null; p4_knowledge?: number | null; p4_inspiration?: number | null; p4_community_resource?: number | null; p4_future_return?: number | null; feedback?: string | null };
export type DashboardActivityLearningCenter = { activity_id: string; learning_center_id: string };
export type DashboardActivityOrganizer = { activity_id: string; organization_id: string; organizer_role: "primary" | "co" };
export type DashboardActivityMedia = { id: string; activity_id: string; occurrence_id?: string | null; public_url: string; media_type: string; caption?: string | null; is_post_event: boolean; display_order: number; status: string; created_at: string };
export type AdminDashboardData = { activities: DashboardActivity[]; occurrences: DashboardOccurrence[]; learningCenters: DashboardLearningCenter[]; organizations: DashboardOrganization[]; surveys: DashboardSurvey[]; responses: DashboardResponse[]; activityLearningCenters: DashboardActivityLearningCenter[]; activityOrganizers: DashboardActivityOrganizer[]; activityMedia: DashboardActivityMedia[] };
export class ApiError extends Error { readonly status: number; constructor(message: string, status: number) { super(message); this.name = "ApiError"; this.status = status; } }
function isRecord(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null; }
const pendingGets = new Map<string, Promise<unknown>>(); const GET_CACHE_TTL_MS = 30_000; const MAX_GET_CACHE_ENTRIES = 100; const getCache = new Map<string, { expiresAt: number; value: unknown }>();
const CACHEABLE_GET_PREFIXES = ["/api/products", "/api/activities", "/api/activity", "/api/centers", "/api/projects"];
function isCacheableGet(url: string) { try { const pathname = new URL(url, window.location.origin).pathname; return CACHEABLE_GET_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`)); } catch { return false; } }
async function request<T>(url: string, init: RequestInit = {}): Promise<T> { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 12_000); try { const headers = new Headers(init.headers); headers.set("Accept", "application/json"); if (init.body !== undefined && !headers.has("Content-Type")) headers.set("Content-Type", "application/json"); const r = await fetch(url, { ...init, signal: init.signal ?? controller.signal, headers }); const p: unknown = await r.json().catch(() => null); if (!r.ok) { const m = isRecord(p) && typeof p.error === "string" ? p.error : "คำขอไม่สำเร็จ"; throw new ApiError(m, r.status); } return isRecord(p) && p.data !== undefined ? p.data as T : p as T; } catch (error) { if (error instanceof ApiError) throw error; throw new ApiError(error instanceof DOMException && error.name === "AbortError" ? "บริการใช้เวลานานเกินไป" : "ไม่สามารถเชื่อมต่อบริการได้", 0); } finally { window.clearTimeout(timeout); } }
export async function apiRequest<T>(url: string, init?: RequestInit): Promise<T> { const method = (init?.method ?? "GET").toUpperCase(); if (method !== "GET" || !isCacheableGet(url)) return request<T>(url, init); const cached = getCache.get(url); if (cached && cached.expiresAt > Date.now()) { getCache.delete(url); getCache.set(url, cached); return cached.value as T; } if (cached) getCache.delete(url); const pending = pendingGets.get(url); if (pending) return pending as Promise<T>; const promise = request<T>(url, init).then((value) => { getCache.delete(url); if (getCache.size >= MAX_GET_CACHE_ENTRIES) { const oldestKey = getCache.keys().next().value; if (oldestKey) getCache.delete(oldestKey); } getCache.set(url, { expiresAt: Date.now() + GET_CACHE_TTL_MS, value }); pendingGets.delete(url); return value; }).catch((error) => { pendingGets.delete(url); throw error; }); pendingGets.set(url, promise); return promise; }
export function invalidateApiCache(prefix?: string) { if (!prefix) { getCache.clear(); return; } for (const key of getCache.keys()) if (key.startsWith(prefix)) getCache.delete(key); }
function standardsFromProduction(raw: Record<string, unknown>): Product["standards"] { const values = new Set<Product["standards"][number]>(); const text = `${String(raw.category ?? "")} ${String(raw.researchTag ?? "")}`.toLowerCase(); if (text.includes("organic") || text.includes("ออร์แกนิก")) values.add("Organic 100%"); if (text.includes("gap")) values.add("GAP"); if (raw.researchTag || text.includes("วิจัย") || text.includes("research")) values.add("งานวิจัย"); return [...values]; }
export async function getProducts(): Promise<Product[]> { const data = await apiRequest<unknown[]>("/api/products"); if (!Array.isArray(data)) return []; return data.flatMap((raw) => { if (!isRecord(raw) || typeof raw.id !== "string" || typeof raw.name !== "string") return []; const base = MOCK_PRODUCTS.find((x) => x.name === raw.name) ?? MOCK_PRODUCTS[0]; if (!base) return []; const price = Number(raw.price ?? 0); const stock = Number(raw.stockQuantity ?? 0); return [{ ...base, id: raw.id, name: raw.name, image: typeof raw.imageUrl === "string" && raw.imageUrl ? raw.imageUrl : "/mahidol-logo.png", standards: standardsFromProduction(raw), price: Number.isFinite(price) ? price : 0, unit: typeof raw.unit === "string" ? raw.unit : "หน่วย", stock: Number.isFinite(stock) ? stock : 0, isPreOrder: raw.isPreorder === true, harvestDate: typeof raw.harvestDate === "string" ? raw.harvestDate : undefined, plotId: typeof raw.plotId === "string" ? raw.plotId : "", description: typeof raw.description === "string" ? raw.description : "", category: typeof raw.category === "string" ? raw.category : "", researchTag: typeof raw.researchTag === "string" ? raw.researchTag : "" }]; }); }
export async function createProduct(p: ProductWriteInput) { const result = await apiRequest("/api/products", { method: "POST", body: JSON.stringify(p) }); invalidateApiCache("/api/products"); return result; }
export async function updateProduct(p: ProductWriteInput & { id: string }) { const result = await apiRequest(`/api/products?id=${encodeURIComponent(p.id)}`, { method: "PUT", body: JSON.stringify(p) }); invalidateApiCache("/api/products"); return result; }
export async function deleteProduct(id: string) { await apiRequest(`/api/products?id=${encodeURIComponent(id)}`, { method: "DELETE" }); invalidateApiCache("/api/products"); }
export async function updateInventory(id: string, stock: number) { const result = await apiRequest(`/api/inventory?id=${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ stock }) }); invalidateApiCache("/api/products"); return result; }
export async function uploadSlip(file: File): Promise<string> { const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("อ่านไฟล์ไม่สำเร็จ")); reader.onerror = () => reject(new Error("อ่านไฟล์ไม่สำเร็จ")); reader.readAsDataURL(file); }); const result = await apiRequest<{ path: string }>("/api/uploads/slip", { method: "POST", body: JSON.stringify({ fileName: file.name, contentType: file.type, dataUrl }) }); return result.path; }
export async function createOrder(input: CreateOrderInput) { return apiRequest("/api/orders", { method: "POST", body: JSON.stringify(input) }); }
export async function getAdminOrders(): Promise<AdminOrder[]> { const d = await apiRequest<AdminOrder[]>("/api/orders"); return Array.isArray(d) ? d : []; }
export async function updateOrderStatus(id: string, status: OrderStatus) { return apiRequest(`/api/orders?id=${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ status }) }); }
export async function getAdminActivities(): Promise<AdminActivity[]> { const d = await apiRequest<AdminActivity[]>("/api/admin/activities"); return Array.isArray(d) ? d : []; }
export async function createActivity(input: ActivityWriteInput) { const result = await apiRequest("/api/admin/activities", { method: "POST", body: JSON.stringify(input) }); invalidateApiCache("/api/admin/activities"); invalidateApiCache("/api/activities"); return result; }
export async function updateActivity(input: ActivityWriteInput & { id: string }) { const result = await apiRequest(`/api/admin/activities?id=${encodeURIComponent(input.id)}`, { method: "PUT", body: JSON.stringify(input) }); invalidateApiCache("/api/admin/activities"); invalidateApiCache("/api/activities"); return result; }
export async function deleteActivity(id: string) { await apiRequest(`/api/admin/activities?id=${encodeURIComponent(id)}`, { method: "DELETE" }); invalidateApiCache("/api/admin/activities"); invalidateApiCache("/api/activities"); }
export async function getAdminDashboardData(): Promise<AdminDashboardData> { return apiRequest<AdminDashboardData>("/api/admin/dashboard"); }
export type EvBookingInput = { customerName: string; customerPhone: string; vehiclePlate: string; startAt: string; endAt: string }; export type EvBookingResult = { id: string; persisted: "api" | "local" };
export async function createEvBooking(input: EvBookingInput): Promise<EvBookingResult> { try { return { id: (await apiRequest<{ id: string }>("/api/ev-bookings", { method: "POST", body: JSON.stringify(input) })).id, persisted: "api" }; } catch (e) { if (!(e instanceof ApiError) || (e.status !== 0 && e.status !== 404 && e.status < 500)) throw e; const id = crypto.randomUUID(), key = "mahidol-lampang-ev-bookings-v1", old = JSON.parse(localStorage.getItem(key) ?? "[]"); localStorage.setItem(key, JSON.stringify([...(Array.isArray(old) ? old : []), { ...input, id, status: "pending" }])); return { id, persisted: "local" }; } }