import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, BookOpen, CheckCircle2, ChevronRight, CloudSun, Droplets, FileText, Leaf, Menu, Search, ShoppingCart, Sprout, Sun, Thermometer, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { CartProvider } from "../storefront/CartContext";
import { useCart } from "../storefront/useCart";
import { CartDrawer } from "../storefront/CartDrawer";
import { MOCK_PRODUCTS, type Product } from "../storefront/mockData";

type Module = { label: string; title: string; description: string; href: string; icon: typeof Leaf; tone: string };
const modules: Module[] = [
  { label: "PORTAL", title: "ภาพรวมศูนย์", description: "ข่าวสาร กิจกรรม และบริการวิชาการ", href: "#overview", icon: Sprout, tone: "bg-[#002D62]" },
  { label: "ห้องคลัง", title: "คลังความรู้", description: "งานวิจัย คู่มือ และข้อมูลเปิด", href: "#knowledge", icon: BookOpen, tone: "bg-[#173f72]" },
  { label: "SMART FARM", title: "เกษตรอัจฉริยะ", description: "ติดตามแปลงเพาะปลูกแบบเรียลไทม์", href: "/smart-farm", icon: Leaf, tone: "bg-[#2E7D32]" },
  { label: "CLEAN ENERGY", title: "พลังงานสะอาด", description: "วิเคราะห์การผลิตและคาร์บอนที่ลดได้", href: "/clean-energy", icon: Zap, tone: "bg-[#9b6a00]" },
  { label: "SHOPPING VEG", title: "ตลาดผักมหิดล", description: "ผลผลิตปลอดภัยจากแปลงวิจัย", href: "#market", icon: ShoppingCart, tone: "bg-[#496b1d]" },
];
const knowledge = [
  { type: "RESEARCH", title: "การบริหารจัดการระบบ Smart Farm ในพื้นที่แห้งแล้ง", meta: "เกษตรอัจฉริยะ · 4 นาที", color: "text-[#2E7D32]" },
  { type: "GUIDE", title: "คู่มือการใช้งานและดูแลแปลงผักปลอดภัย", meta: "คู่มือเกษตร · ดาวน์โหลด PDF", color: "text-[#002D62]" },
  { type: "ENERGY", title: "รายงานผลการผลิตไฟฟ้าจาก Solar Rooftop", meta: "พลังงานสะอาด · 2 นาที", color: "text-[#9b6a00]" },
];
function CartButton() { const { totalItems, setIsCartOpen } = useCart(); return <button onClick={() => setIsCartOpen(true)} className="relative rounded-xl border border-white/20 p-2.5 transition hover:bg-white/10" aria-label="เปิดรถเข็น"><ShoppingCart size={19} />{totalItems > 0 && <span className="absolute -right-2 -top-2 flex h-5 min-w-5 items-center justify-center rounded-full bg-[#F2A900] px-1 text-[10px] font-bold text-[#002D62]">{totalItems}</span>}</button>; }
function Telemetry({ icon: Icon, label, value, unit, status, color }: { icon: typeof Droplets; label: string; value: string; unit: string; status: string; color: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className={`rounded-lg p-2 ${color}`}><Icon size={18} /></span><span className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-[#2E7D32]"><CheckCircle2 size={13} />{status}</span></div><p className="mt-4 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-[#002D62]">{value}<span className="ml-1 text-xs font-medium text-slate-400">{unit}</span></p></div>; }
function MarketCard({ product }: { product: Product }) { const { addItem } = useCart(); return <article className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative h-40 overflow-hidden bg-slate-100"><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold text-[#2E7D32] backdrop-blur-md">GAP CERTIFIED</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold leading-snug text-[#002D62]">{product.name}</h3><span className="whitespace-nowrap text-base font-bold text-[#002D62]">฿{product.price}<small className="text-[10px] font-normal text-slate-400">/{product.unit}</small></span></div><p className="mt-2 flex items-center gap-1 text-[11px] text-[#2E7D32]"><CloudSun size={13} /> IoT Monitored · แปลง {product.plotId}</p><button onClick={() => addItem(product)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#002D62] py-2.5 text-xs font-bold text-white transition hover:bg-[#17497f]"><ShoppingCart size={14} /> เพิ่มลงตะกร้า</button></div></article>; }

export function MahidolLampangHub() {
  const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(""); const products = MOCK_PRODUCTS.slice(0, 3);
  const filteredKnowledge = useMemo(() => knowledge.filter((item) => `${item.title} ${item.type}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <CartProvider><div className="min-h-screen bg-zinc-50 text-slate-800" id="overview">
    <header className="sticky top-0 z-50 bg-[#002D62] text-white shadow-lg"><div className="mx-auto flex max-w-7xl items-center gap-5 px-4 py-3 lg:px-8"><a href="#overview" className="flex min-w-0 items-center gap-3"><img src="/mahidol-logo.png" alt="Mahidol University" className="h-10 w-10 rounded-lg bg-white object-contain p-1" /><div className="hidden min-w-0 sm:block"><p className="truncate text-sm font-bold">Mahidol University</p><p className="truncate text-[10px] text-blue-200">Lampang Hub Portal</p></div></a><nav className="ml-auto hidden items-center gap-6 text-xs font-medium text-blue-100 lg:flex"><a href="#modules" className="hover:text-[#F2A900]">ระบบทั้งหมด</a><a href="#farm" className="hover:text-[#F2A900]">สถานะฟาร์ม</a><a href="#market" className="hover:text-[#F2A900]">ตลาดผัก</a><a href="#knowledge" className="hover:text-[#F2A900]">ห้องคลัง</a></nav><div className="ml-auto flex items-center gap-2 lg:ml-4"><div className="hidden items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2 md:flex"><Search size={15} className="text-blue-200" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหาในพอร์ทัล" className="w-32 bg-transparent text-xs outline-none placeholder:text-blue-200" /></div><CartButton /><button className="rounded-xl p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div>{menuOpen && <div className="border-t border-white/10 px-4 pb-4 pt-2 lg:hidden"><a className="block py-2 text-sm" href="#modules" onClick={() => setMenuOpen(false)}>ระบบทั้งหมด</a><a className="block py-2 text-sm" href="#market" onClick={() => setMenuOpen(false)}>ตลาดผัก</a><a className="block py-2 text-sm" href="#knowledge" onClick={() => setMenuOpen(false)}>ห้องคลัง</a></div>}</header>
    <main><section className="relative overflow-hidden bg-[#002D62] pb-20 pt-12 text-white lg:pb-28 lg:pt-20"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "url('/banner2.jpg')", backgroundSize: "cover", backgroundPosition: "center" }} /><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-4 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#F2A900]/50 bg-[#F2A900]/15 px-3 py-1.5 text-[10px] font-bold tracking-[.18em] text-[#F2A900]"><span className="h-1.5 w-1.5 rounded-full bg-[#F2A900]" /> CONNECTED ECOSYSTEM</span><h1 className="mt-5 max-w-2xl text-4xl font-bold leading-tight md:text-6xl">มหิดลลำปาง<br /><span className="text-[#F2A900]">Hub Portal</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-blue-100 md:text-base">เชื่อมต่อองค์ความรู้ งานวิจัย นวัตกรรม และชุมชน เพื่ออนาคตที่ยั่งยืนของลำปาง</p><div className="mt-7 flex flex-wrap gap-3"><a href="#modules" className="inline-flex items-center gap-2 rounded-xl bg-[#F2A900] px-5 py-3 text-xs font-bold text-[#002D62] transition hover:-translate-y-0.5">สำรวจระบบทั้งหมด <ArrowUpRight size={15} /></a><a href="#market" className="inline-flex items-center gap-2 rounded-xl border border-white/25 px-5 py-3 text-xs font-bold text-white transition hover:bg-white/10">เลือกซื้อผลผลิต <ShoppingCart size={15} /></a></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur-md"><p className="text-[10px] uppercase tracking-widest text-blue-200">Live systems</p><p className="mt-3 text-4xl font-bold text-[#F2A900]">05</p><p className="mt-1 text-xs text-blue-100">ระบบที่เชื่อมต่ออยู่</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur-md"><p className="text-[10px] uppercase tracking-widest text-blue-200">Solar today</p><p className="mt-3 text-4xl font-bold">42.8<span className="text-sm text-blue-200"> kWh</span></p><p className="mt-1 text-xs text-[#7bd67f]">↑ 12.4% จากเมื่อวาน</p></div><div className="col-span-2 rounded-2xl border border-[#F2A900]/30 bg-[#F2A900]/10 p-5 backdrop-blur-md"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-widest text-[#F2A900]">Portal status</p><p className="mt-2 text-sm font-semibold">ทุกระบบทำงานเป็นปกติ</p></div><CheckCircle2 className="text-[#7bd67f]" /><span className="text-[10px] text-blue-200">อัปเดตล่าสุด 10:42 น.</span></div></div></div></div></section>
    <section id="modules" className="relative z-10 mx-auto -mt-10 max-w-7xl px-4 lg:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{modules.map(({ icon: Icon, ...module }) => <a key={module.title} href={module.href} className={`group rounded-2xl ${module.tone} p-4 text-white shadow-xl transition hover:-translate-y-1`}><div className="flex items-center justify-between"><Icon size={21} /><ArrowUpRight size={16} className="opacity-60 transition group-hover:opacity-100" /></div><p className="mt-5 text-[9px] font-bold tracking-[.18em] text-white/60">{module.label}</p><h2 className="mt-1 text-sm font-bold">{module.title}</h2><p className="mt-1 text-[11px] leading-5 text-white/75">{module.description}</p></a>)}</div></section>
    <section id="farm" className="mx-auto max-w-7xl px-4 py-16 lg:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#2E7D32]">SMART FARM / LIVE TELEMETRY</p><h2 className="mt-2 text-2xl font-bold text-[#002D62] md:text-3xl">สถานะแปลงสาธิตวันนี้</h2><p className="mt-2 text-sm text-slate-500">ข้อมูลจากเซนเซอร์แปลงเกษตรอัจฉริยะ อัปเดตทุก 5 นาที</p></div><Link to="/smart-farm" className="flex items-center gap-1 text-xs font-bold text-[#002D62]">ดูแดชบอร์ดเต็ม <ChevronRight size={16} /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Telemetry icon={Droplets} label="ความชื้นในดิน" value="61" unit="%" status="Ready" color="bg-green-50 text-[#2E7D32]" /><Telemetry icon={Thermometer} label="อุณหภูมิ" value="25.8" unit="°C" status="Normal" color="bg-amber-50 text-[#9b6a00]" /><Telemetry icon={CloudSun} label="ความชื้นสัมพัทธ์" value="68" unit="%" status="Normal" color="bg-blue-50 text-[#002D62]" /></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-12 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#9b6a00]">CLEAN ENERGY ANALYTICS</p><h2 className="mt-2 text-2xl font-bold text-[#002D62]">พลังงานสะอาดที่สร้างผลลัพธ์</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">ติดตามพลังงานจากแสงอาทิตย์และผลกระทบเชิงบวกต่อสิ่งแวดล้อมแบบโปร่งใส</p><Link to="/clean-energy" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#002D62] px-4 py-2.5 text-xs font-bold text-white">เปิด Energy dashboard <ArrowUpRight size={14} /></Link></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-amber-50 p-4"><Sun className="text-[#F2A900]" size={20} /><p className="mt-4 text-xs text-slate-500">ผลิตไฟฟ้าวันนี้</p><p className="mt-1 text-2xl font-bold text-[#002D62]">42.8 <small className="text-xs">kWh</small></p></div><div className="rounded-2xl bg-green-50 p-4"><Leaf className="text-[#2E7D32]" size={20} /><p className="mt-4 text-xs text-slate-500">ลด CO₂ สะสม</p><p className="mt-1 text-2xl font-bold text-[#2E7D32]">1.24 <small className="text-xs">tCO₂e</small></p></div></div></div></section>
    <section id="market" className="mx-auto max-w-7xl px-4 py-16 lg:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#2E7D32]">SHOPPING VEG MARKETPLACE</p><h2 className="mt-2 text-2xl font-bold text-[#002D62] md:text-3xl">ผลผลิตจากแปลงวิจัย</h2><p className="mt-2 text-sm text-slate-500">สด ปลอดภัย ตรวจสอบย้อนกลับได้ด้วย IoT</p></div><button onClick={() => toast.info("กำลังเปิดดูผลผลิตทั้งหมด")} className="flex items-center gap-1 text-xs font-bold text-[#002D62]">ดูสินค้าทั้งหมด <ChevronRight size={16} /></button></div><div className="mt-7 grid gap-5 md:grid-cols-3">{products.map((product) => <MarketCard key={product.id} product={product} />)}</div></section>
    <section id="knowledge" className="bg-[#f4f6f9] py-16"><div className="mx-auto max-w-7xl px-4 lg:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#002D62]">KNOWLEDGE REPOSITORY</p><h2 className="mt-2 text-2xl font-bold text-[#002D62] md:text-3xl">ห้องคลังความรู้</h2><p className="mt-2 text-sm text-slate-500">ข้อมูลสำหรับการเรียนรู้ วิจัย และต่อยอดชุมชน</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2"><Search size={15} className="text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหาเอกสาร..." className="w-40 bg-transparent text-xs outline-none" /></div></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{filteredKnowledge.map((item) => <article key={item.title} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className={`text-[10px] font-bold tracking-widest ${item.color}`}>{item.type}</span><FileText size={18} className="text-slate-300" /></div><h3 className="mt-8 text-sm font-bold leading-6 text-[#002D62]">{item.title}</h3><p className="mt-2 text-[11px] text-slate-500">{item.meta}</p><button onClick={() => toast.success("เปิดเอกสารในห้องคลังแล้ว")} className="mt-5 flex items-center gap-1 text-xs font-bold text-[#002D62]">อ่านเพิ่มเติม <ArrowUpRight size={14} /></button></article>)}</div></div></section></main>
    <footer className="bg-[#002D62] text-blue-100"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 md:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><div className="flex items-center gap-3"><img src="/mahidol-logo.png" alt="Mahidol University" className="h-9 w-9 rounded bg-white p-1" /><p className="font-bold text-white">Mahidol Lampang Hub</p></div><p className="mt-4 max-w-sm text-xs leading-6 text-blue-200">ศูนย์การเรียนรู้ วิจัย และบริการวิชาการ มหาวิทยาลัยมหิดล อำเภอสบปราบ จังหวัดลำปาง</p></div><div><p className="text-xs font-bold text-[#F2A900]">QUICK LINKS</p><a href="#knowledge" className="mt-4 block text-xs hover:text-white">ห้องคลังความรู้</a><a href="#market" className="mt-3 block text-xs hover:text-white">ตลาดผักมหิดล</a><a href="/smart-farm" className="mt-3 block text-xs hover:text-white">Smart Farm IoT</a></div><div><p className="text-xs font-bold text-[#F2A900]">SYSTEM STATUS</p><p className="mt-4 flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full bg-[#7bd67f]" /> All systems operational</p><p className="mt-3 text-xs text-blue-300">© 2026 Mahidol University</p></div></div></footer><CartDrawer /></div></CartProvider>;
}
