import { getSupabaseRestConfig, json, methodNotAllowed, supabaseRest } from "./_supabase-rest";

type Env = Record<string, unknown>;
type ActivityRow = Record<string, unknown>;
type MediaRow = { activity_id: string; public_url: string | null; display_order: number; created_at: string };
const SELECT = "id,title,activity_date,category,featured_image,images,objective,key_activities,outcomes,participants,status,created_at,updated_at,survey_enabled,survey_open_at,survey_close_at,survey_welcome_text";
function toActivity(row: ActivityRow, media: MediaRow[] = []) { const stored = media.filter((item) => item.public_url).sort((a, b) => a.display_order - b.display_order || b.created_at.localeCompare(a.created_at)).map((item) => String(item.public_url)); const images = [...stored, ...(Array.isArray(row.images) ? row.images.map(String) : [])].filter((url, index, list) => url && list.indexOf(url) === index); return { id: String(row.id), slug: String(row.id), title: String(row.title ?? ""), summary: String(row.objective ?? row.outcomes ?? "กิจกรรมพันธกิจเพื่อสังคม"), activityDate: String(row.activity_date ?? ""), location: "พื้นที่ปฏิบัติการลำปาง", featuredImage: String(row.featured_image ?? "") || images[0] || "/main banner.jpg", objective: String(row.objective ?? ""), process: Array.isArray(row.key_activities) ? row.key_activities.join("\n") : String(row.key_activities ?? ""), outcome: String(row.outcomes ?? ""), impact: "", participantCount: Number.isFinite(Number(row.participants)) ? Number(row.participants) : undefined, category: String(row.category ?? ""), status: String(row.status ?? "draft"), images, surveyEnabled: row.survey_enabled === true, surveyOpenAt: row.survey_open_at ?? null, surveyCloseAt: row.survey_close_at ?? null, surveyWelcomeText: row.survey_welcome_text ?? null, createdAt: String(row.created_at ?? ""), updatedAt: String(row.updated_at ?? "") }; }
export async function onRequestGet({ env }: { env: Env }) { if (!getSupabaseRestConfig(env).configured) return json({ error: "Supabase is not configured" }, 503); try { const rows = await supabaseRest<ActivityRow[]>(env, "activities", { select: SELECT, status: "eq.published", order: "activity_date.desc" }); const media = rows.length ? await supabaseRest<MediaRow[]>(env, "activity_media", { select: "activity_id,public_url,display_order,created_at", activity_id: `in.(${rows.map((row) => String(row.id)).join(",")})`, status: "eq.active", is_post_event: "eq.true" }) : []; const grouped = new Map<string, MediaRow[]>(); for (const item of media) { const current = grouped.get(item.activity_id) ?? []; current.push(item); grouped.set(item.activity_id, current); } return json({ success: true, data: rows.map((row) => toActivity(row, grouped.get(String(row.id)) ?? [])) }); } catch (error) { console.error("GET /api/activities", error); return json({ error: "ไม่สามารถโหลดกิจกรรมได้" }, 500); } }
export function onRequest({ request, env }: { request: Request; env: Env }) { if (request.method === "GET") return onRequestGet({ env }); return methodNotAllowed("GET"); }
