import { useEffect } from "react";
import { AlertTriangle, Check, X } from "lucide-react";

export type AIApprovalDialogProps = { open: boolean; title: string; summary: string; changes: string[]; onApprove: () => void; onReject: () => void; onClose: () => void };

export function AIApprovalDialog({ open, title, summary, changes, onApprove, onReject, onClose }: AIApprovalDialogProps) {
  useEffect(() => { if (!open) return; const handler = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/40 p-4" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="ai-approval-title"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><AlertTriangle className="h-5 w-5" /></div><div className="min-w-0 flex-1"><h2 id="ai-approval-title" className="text-lg font-bold text-brand-navy">{title}</h2><p className="mt-1 text-sm text-slate-600">{summary}</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="ปิด"><X className="h-4 w-4" /></button></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">สิ่งที่จะเปลี่ยนแปลง</p><ul className="mt-2 space-y-2">{changes.map((change) => <li key={change} className="flex gap-2 text-sm text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{change}</li>)}</ul></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onReject} className="min-h-10 rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-700 hover:bg-slate-50">ไม่อนุมัติ</button><button type="button" onClick={onApprove} className="min-h-10 rounded-xl bg-brand-navy px-4 text-sm font-bold text-white hover:opacity-90">อนุมัติและดำเนินการ</button></div></section></div>;
}
