/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleanEnergyRouteImport } from './routes/clean-energy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RacRouteImport } from './routes/rac'
import { Route as SmartFarmRouteImport } from './routes/smart-farm'
import { Route as SurveyRouteImport } from './routes/survey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanEnergyRoute = CleanEnergyRouteImport.update({
  id: '/clean-energy',
  path: '/clean-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RacRoute = RacRouteImport.update({
  id: '/rac',
  path: '/rac',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartFarmRoute = SmartFarmRouteImport.update({
  id: '/smart-farm',
  path: '/smart-farm',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/survey': typeof SurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/survey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/survey'
  id:
    | '__root__'
    | '/'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanEnergyRoute: typeof CleanEnergyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RacRoute: typeof RacRoute
  SmartFarmRoute: typeof SmartFarmRoute
  SurveyRoute: typeof SurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clean-energy': {
      id: '/clean-energy'
      path: '/clean-energy'
      fullPath: '/clean-energy'
      preLoaderRoute: typeof CleanEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rac': {
      id: '/rac'
      path: '/rac'
      fullPath: '/rac'
      preLoaderRoute: typeof RacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-farm': {
      id: '/smart-farm'
      path: '/smart-farm'
      fullPath: '/smart-farm'
      preLoaderRoute: typeof SmartFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanEnergyRoute: CleanEnergyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RacRoute: RacRoute,
  SmartFarmRoute: SmartFarmRoute,
  SurveyRoute: SurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
