/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CleanEnergyRouteImport } from './routes/clean-energy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RacRouteImport } from './routes/rac'
import { Route as SmartFarmRouteImport } from './routes/smart-farm'
import { Route as StorefrontRouteImport } from './routes/storefront'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as ApiEvBookingsRouteImport } from './routes/api/ev-bookings'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiInventoryIdRouteImport } from './routes/api/inventory/$id'
import { Route as ApiProductsIdRouteImport } from './routes/api/products/$id'
import { Route as ApiAdminOrdersIdStatusRouteImport } from './routes/api/admin/orders/$id/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanEnergyRoute = CleanEnergyRouteImport.update({
  id: '/clean-energy',
  path: '/clean-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RacRoute = RacRouteImport.update({
  id: '/rac',
  path: '/rac',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartFarmRoute = SmartFarmRouteImport.update({
  id: '/smart-farm',
  path: '/smart-farm',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRoute = StorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvBookingsRoute = ApiEvBookingsRouteImport.update({
  id: '/api/ev-bookings',
  path: '/api/ev-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryIdRoute = ApiInventoryIdRouteImport.update({
  id: '/api/inventory/$id',
  path: '/api/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiAdminOrdersIdStatusRoute = ApiAdminOrdersIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiAdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/storefront': typeof StorefrontRoute
  '/survey': typeof SurveyRoute
  '/api/ev-bookings': typeof ApiEvBookingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/storefront': typeof StorefrontRoute
  '/survey': typeof SurveyRoute
  '/api/ev-bookings': typeof ApiEvBookingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clean-energy': typeof CleanEnergyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rac': typeof RacRoute
  '/smart-farm': typeof SmartFarmRoute
  '/storefront': typeof StorefrontRoute
  '/survey': typeof SurveyRoute
  '/api/ev-bookings': typeof ApiEvBookingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/storefront'
    | '/survey'
    | '/api/ev-bookings'
    | '/api/orders'
    | '/api/products'
    | '/api/admin/orders'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/inventory/$id'
    | '/api/products/$id'
    | '/api/admin/orders/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/storefront'
    | '/survey'
    | '/api/ev-bookings'
    | '/api/orders'
    | '/api/products'
    | '/api/admin/orders'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/inventory/$id'
    | '/api/products/$id'
    | '/api/admin/orders/$id/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clean-energy'
    | '/dashboard'
    | '/login'
    | '/rac'
    | '/smart-farm'
    | '/storefront'
    | '/survey'
    | '/api/ev-bookings'
    | '/api/orders'
    | '/api/products'
    | '/api/admin/orders'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/inventory/$id'
    | '/api/products/$id'
    | '/api/admin/orders/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CleanEnergyRoute: typeof CleanEnergyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RacRoute: typeof RacRoute
  SmartFarmRoute: typeof SmartFarmRoute
  StorefrontRoute: typeof StorefrontRoute
  SurveyRoute: typeof SurveyRoute
  ApiEvBookingsRoute: typeof ApiEvBookingsRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiInventoryIdRoute: typeof ApiInventoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clean-energy': {
      id: '/clean-energy'
      path: '/clean-energy'
      fullPath: '/clean-energy'
      preLoaderRoute: typeof CleanEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rac': {
      id: '/rac'
      path: '/rac'
      fullPath: '/rac'
      preLoaderRoute: typeof RacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-farm': {
      id: '/smart-farm'
      path: '/smart-farm'
      fullPath: '/smart-farm'
      preLoaderRoute: typeof SmartFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront': {
      id: '/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ev-bookings': {
      id: '/api/ev-bookings'
      path: '/api/ev-bookings'
      fullPath: '/api/ev-bookings'
      preLoaderRoute: typeof ApiEvBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/$id': {
      id: '/api/inventory/$id'
      path: '/api/inventory/$id'
      fullPath: '/api/inventory/$id'
      preLoaderRoute: typeof ApiInventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/admin/orders/$id/status': {
      id: '/api/admin/orders/$id/status'
      path: '/$id/status'
      fullPath: '/api/admin/orders/$id/status'
      preLoaderRoute: typeof ApiAdminOrdersIdStatusRouteImport
      parentRoute: typeof ApiAdminOrdersRoute
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

interface ApiAdminOrdersRouteChildren {
  ApiAdminOrdersIdStatusRoute: typeof ApiAdminOrdersIdStatusRoute
}

const ApiAdminOrdersRouteChildren: ApiAdminOrdersRouteChildren = {
  ApiAdminOrdersIdStatusRoute: ApiAdminOrdersIdStatusRoute,
}

const ApiAdminOrdersRouteWithChildren = ApiAdminOrdersRoute._addFileChildren(
  ApiAdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CleanEnergyRoute: CleanEnergyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RacRoute: RacRoute,
  SmartFarmRoute: SmartFarmRoute,
  StorefrontRoute: StorefrontRoute,
  SurveyRoute: SurveyRoute,
  ApiEvBookingsRoute: ApiEvBookingsRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiAdminOrdersRoute: ApiAdminOrdersRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiInventoryIdRoute: ApiInventoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
