import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ImagePlus, Pencil, Plus, RefreshCw, Search, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { createActivity, getAdminActivities, updateActivity, type ActivityStatus, type ActivityWriteInput, type AdminActivity } from "@/services/api";
import { getAdminLearningCenters, type LearningCenter } from "@/services/admin-learning-centers";

const blankActivity: ActivityWriteInput = { title: "", slug: "", summary: "", content: "", activityDate: new Date().toISOString().slice(0, 16), location: "", participantCount: 0, objective: "", process: "", outcome: "", impact: "", featuredImage: "", status: "draft" };
const statusLabel: Record<ActivityStatus, string> = { draft: "Draft", published: "Published", scheduled: "Scheduled", ongoing: "Ongoing", completed: "Completed", cancelled: "Cancelled", archived: "Archived" };
function statusClass(s: ActivityStatus) { return s === "completed" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : s === "cancelled" || s === "archived" ? "bg-slate-100 text-slate-600 border-slate-200" : s === "ongoing" ? "bg-blue-50 text-blue-700 border-blue-200" : "bg-amber-50 text-amber-700 border-amber-200"; }

type ActivityMedia = { id: string; public_url: string; caption?: string | null; is_post_event?: boolean; status?: string };
type RelationState = { learningCenterIds: string[]; organizations: Array<{ organizationId: string; organizerRole?: string }> };

async function getRelations(activityId: string): Promise<RelationState> { const response = await fetch(`/api/admin/activity-relations?activityId=${encodeURIComponent(activityId)}`, { credentials: "include", headers: { Accept: "application/json" } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "โหลดข้อมูลที่เกี่ยวข้องไม่สำเร็จ"); return body.data as RelationState; }
async function saveRelations(activityId: string, relation: RelationState) { const response = await fetch(`/api/admin/activity-relations?activityId=${encodeURIComponent(activityId)}`, { method: "PUT", credentials: "include", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify(relation) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "บันทึกข้อมูลที่เกี่ยวข้องไม่สำเร็จ"); }
async function getMedia(activityId: string): Promise<ActivityMedia[]> { const response = await fetch(`/api/admin/activity-media?activityId=${encodeURIComponent(activityId)}`, { credentials: "include", headers: { Accept: "application/json" } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "โหลดรูปภาพไม่สำเร็จ"); return Array.isArray(body.data) ? body.data : []; }
async function uploadMedia(activityId: string, file: File) { const form = new FormData(); form.set("activityId", activityId); form.set("file", file); const response = await fetch("/api/admin/activity-media", { method: "POST", credentials: "include", body: form }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || "อัปโหลดรูปภาพไม่สำเร็จ"); return body.data as ActivityMedia; }

export function ActivitiesManagementPage() {
  const [activities, setActivities] = useState<AdminActivity[]>([]), [centers, setCenters] = useState<LearningCenter[]>([]), [q, setQ] = useState(""), [status, setStatus] = useState<"all" | ActivityStatus>("all"), [edit, setEdit] = useState<AdminActivity | null>(null), [form, setForm] = useState<ActivityWriteInput>(blankActivity), [selectedCenters, setSelectedCenters] = useState<string[]>([]), [organizers, setOrganizers] = useState<RelationState["organizations"]>([]), [media, setMedia] = useState<ActivityMedia[]>([]), [files, setFiles] = useState<File[]>([]), [open, setOpen] = useState(false), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false);
  async function load() { setLoading(true); try { setActivities(await getAdminActivities()); } catch (e) { toast.error(e instanceof Error ? e.message : "โหลดกิจกรรมไม่สำเร็จ"); } finally { setLoading(false); } }
  useEffect(() => { void load(); void getAdminLearningCenters().then(setCenters).catch(() => setCenters([])); }, []);
  const filtered = useMemo(() => { const needle = q.trim().toLowerCase(); return activities.filter((x) => (status === "all" || x.status === status) && (!needle || `${x.title} ${x.slug} ${x.location ?? ""}`.toLowerCase().includes(needle))); }, [activities, q, status]);
  function create() { setEdit(null); setForm({ ...blankActivity, activityDate: new Date().toISOString().slice(0, 16) }); setSelectedCenters([]); setOrganizers([]); setMedia([]); setFiles([]); setOpen(true); }
  async function openEdit(x: AdminActivity) { setEdit(x); setForm({ ...x }); setFiles([]); setOpen(true); try { const [relation, images] = await Promise.all([getRelations(x.id), getMedia(x.id)]); setSelectedCenters(relation.learningCenterIds ?? []); setOrganizers(relation.organizations ?? []); setMedia(images); } catch (e) { toast.error(e instanceof Error ? e.message : "โหลดข้อมูลกิจกรรมเพิ่มเติมไม่สำเร็จ"); setSelectedCenters([]); setOrganizers([]); setMedia([]); } }
  async function save() {
    if (!form.title.trim() || !form.activityDate) { toast.error("กรุณาระบุชื่อกิจกรรมและวันที่"); return; }
    setSaving(true);
    try {
      const saved = edit ? await updateActivity({ ...form, id: edit.id }) : await createActivity(form);
      const activity = saved as AdminActivity;
      if (!activity?.id) throw new Error("ไม่พบรหัสกิจกรรมหลังบันทึก");
      await saveRelations(activity.id, { learningCenterIds: selectedCenters, organizations: organizers });
      if (files.length) {
        setUploading(true);
        const uploaded: ActivityMedia[] = [];
        for (const file of files) uploaded.push(await uploadMedia(activity.id, file));
        setMedia((current) => [...uploaded, ...current]);
        if (!form.featuredImage && uploaded[0]?.public_url) await updateActivity({ ...form, id: activity.id, featuredImage: uploaded[0].public_url });
        setFiles([]);
      }
      toast.success(edit ? "อัปเดตกิจกรรมแล้ว" : "สร้างกิจกรรมแล้ว"); setOpen(false); setEdit(null); await load();
    } catch (e) { toast.error(e instanceof Error ? e.message : "บันทึกกิจกรรมไม่สำเร็จ"); } finally { setSaving(false); setUploading(false); }
  }
  return <section className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-emerald-700">Activity Management</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-brand-navy lg:text-3xl">จัดการกิจกรรม</h1><p className="mt-1 text-sm text-slate-600">กิจกรรมเป็นจุดเดียวสำหรับข้อมูล ศูนย์การเรียนรู้ และรูปภาพ</p></div><div className="flex gap-2"><button type="button" onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-brand-navy"><RefreshCw className="h-4 w-4" />รีเฟรช</button><button type="button" onClick={create} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-navy px-4 text-sm font-bold text-white"><Plus className="h-4 w-4" />เพิ่มกิจกรรม</button></div></div>
    <div className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_220px]"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><span className="sr-only">ค้นหากิจกรรม</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="ค้นหาชื่อกิจกรรม, slug หรือสถานที่" className="dashboard-control w-full pl-10" /></label><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="dashboard-control"><option value="all">ทุกสถานะ</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <div className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-10 text-center text-sm text-slate-500">กำลังโหลดกิจกรรม...</div> : filtered.length === 0 ? <div className="p-10 text-center text-sm text-slate-500">ไม่พบกิจกรรมตามเงื่อนไข</div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3 text-left">กิจกรรม</th><th className="px-4 py-3 text-left">วันที่</th><th className="px-4 py-3 text-left">สถานที่</th><th className="px-4 py-3 text-center">ผู้เข้าร่วม</th><th className="px-4 py-3 text-center">สถานะ</th><th className="px-5 py-3 text-right">จัดการ</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((x) => <tr key={x.id} className="hover:bg-slate-50/80"><td className="px-5 py-4"><div className="flex items-center gap-3">{x.featuredImage ? <img src={x.featuredImage} alt="" className="h-12 w-16 rounded-lg object-cover" /> : <div className="grid h-12 w-16 place-items-center rounded-lg bg-slate-100 text-slate-400"><ImagePlus className="h-5 w-5" /></div>}<div className="min-w-0"><p className="font-semibold text-slate-900">{x.title}</p><p className="mt-0.5 truncate text-xs text-slate-400">/{x.slug}</p></div></div></td><td className="whitespace-nowrap px-4 py-4 text-slate-600"><span className="inline-flex items-center gap-1.5"><CalendarDays className="h-4 w-4 text-slate-400" />{new Date(x.activityDate).toLocaleDateString("th-TH")}</span></td><td className="max-w-[180px] truncate px-4 py-4 text-slate-600">{x.location || "—"}</td><td className="px-4 py-4 text-center font-semibold text-slate-700">{x.participantCount ?? 0}</td><td className="px-4 py-4 text-center"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${statusClass(x.status)}`}>{statusLabel[x.status]}</span></td><td className="px-5 py-4 text-right"><button type="button" onClick={() => void openEdit(x)} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-brand-navy"><Pencil className="h-3.5 w-3.5" />แก้ไข</button></td></tr>)}</tbody></table></div>}</div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="text-lg font-bold text-brand-navy">{edit ? "แก้ไขกิจกรรม" : "เพิ่มกิจกรรม"}</h2><button type="button" onClick={() => setOpen(false)} aria-label="ปิด"><X className="h-5 w-5" /></button></div>
      <div className="overflow-y-auto p-5">
        <div className="grid gap-4 md:grid-cols-2">{([["title", "ชื่อกิจกรรม", "text"], ["slug", "Slug", "text"], ["activityDate", "วันที่", "date"], ["location", "สถานที่", "text"], ["participantCount", "จำนวนผู้เข้าร่วม", "number"]] as const).map(([key, label, type]) => <label key={key} className="block text-sm font-semibold text-slate-700">{label}<input type={type} value={String(form[key] ?? "").slice(0, type === "date" ? 10 : undefined)} onChange={(e) => setForm((current) => ({ ...current, [key]: key === "participantCount" ? Number(e.target.value) : e.target.value }))} className="dashboard-control mt-1 w-full" /></label>)}<label className="block text-sm font-semibold text-slate-700">สถานะ<select value={form.status} onChange={(e) => setForm((current) => ({ ...current, status: e.target.value as ActivityStatus }))} className="dashboard-control mt-1 w-full">{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
        <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="text-sm font-bold text-brand-navy">ศูนย์การเรียนรู้ที่เกี่ยวข้อง</h3><p className="mt-1 text-xs text-slate-500">เลือกจากข้อมูล Master Data ระหว่างบันทึกกิจกรรม ไม่ต้องจัดการความสัมพันธ์แยก</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{centers.length ? centers.map((center) => <label key={center.id} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={selectedCenters.includes(center.id)} onChange={(e) => setSelectedCenters((current) => e.target.checked ? [...current, center.id] : current.filter((id) => id !== center.id))} />{center.name}</label>) : <p className="text-sm text-slate-500">ยังไม่มีข้อมูลศูนย์การเรียนรู้</p>}</div></div>
        <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-brand-navy">รูปภาพกิจกรรม</h3><p className="mt-1 text-xs text-slate-500">อัปโหลดจากหน้ากิจกรรมโดยตรง · JPEG, PNG หรือ WebP ไม่เกิน 10MB/ไฟล์</p></div><label className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-brand-navy"><Upload className="h-4 w-4" />เพิ่มรูป<input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /></label></div>{files.length > 0 && <p className="mt-3 text-xs font-medium text-emerald-700">เตรียมอัปโหลด {files.length} ไฟล์เมื่อกดบันทึก</p>}{media.length > 0 && <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{media.map((image) => <img key={image.id} src={image.public_url} alt={image.caption ?? "ภาพกิจกรรม"} className="aspect-[4/3] w-full rounded-xl object-cover" />)}</div>}</div>
        <div className="mt-5 grid gap-4 md:grid-cols-2">{([["summary", "สรุปกิจกรรม"], ["objective", "วัตถุประสงค์"], ["process", "กระบวนการ / กิจกรรมที่ดำเนินการ"], ["outcome", "ผลลัพธ์"], ["impact", "ผลกระทบ / ประโยชน์"], ["content", "รายละเอียดกิจกรรม"]] as const).map(([key, label]) => <label key={key} className="block text-sm font-semibold text-slate-700">{label}<textarea rows={key === "content" ? 5 : 3} value={String(form[key] ?? "")} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className="dashboard-control mt-1 w-full" /></label>)}</div>
      </div><div className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4"><button type="button" onClick={() => setOpen(false)} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-semibold">ยกเลิก</button><button type="button" disabled={saving || uploading} onClick={() => void save()} className="min-h-11 rounded-xl bg-brand-navy px-5 text-sm font-bold text-white disabled:opacity-60">{uploading ? "กำลังอัปโหลดรูป..." : saving ? "กำลังบันทึก..." : "บันทึกกิจกรรม"}</button></div></div></div>}
  </section>;
}
