import { useState } from "react";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { AIAccessGuard } from "@/components/ai/AIAccessGuard";
import { AIApprovalDialog } from "@/components/ai/AIApprovalDialog";

export function AIApprovalPage() {
  const [open, setOpen] = useState(false);
  return <AIAccessGuard permission="ai.approval.read"><section className="min-h-[calc(100vh-4rem)] bg-[#f8f9ff] px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-[900px]"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#3f5f8f]">APPROVAL GATE</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight text-[#002d62] sm:text-[28px]">ยืนยันการทำงานของ AI</h1><p className="mt-1 text-sm text-slate-600">ตรวจสอบสิ่งที่ AI เตรียมไว้ แล้วอนุมัติเฉพาะ action ที่คุณต้องการให้เกิดขึ้นจริง</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-[#effaf2] px-3 py-1.5 text-[10px] font-bold text-[#2e7d32]"><ShieldCheck className="h-3.5 w-3.5"/> ADMIN DECISION</span></div><div className="mt-5 rounded-xl border border-[#c4c6d1] bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#eff4ff]"><CheckCircle2 className="h-5 w-5 text-[#002d62]"/></div><div><h2 className="text-sm font-bold text-slate-900">Approval component พร้อมใช้งาน</h2><p className="mt-1 text-xs leading-5 text-slate-500">หน้านี้เป็น UI foundation ตาม Stitch; action จริงจะถูกส่งผ่าน policy, Tool Registry และ Portal API เมื่อ backend พร้อม</p></div></div><button type="button" onClick={() => setOpen(true)} className="mt-5 min-h-10 rounded-lg bg-[#002d62] px-4 text-sm font-bold text-white hover:opacity-90">เปิด Approval</button></div></div><AIApprovalDialog open={open} title="ยืนยันการทำงานของ AI" summary="ตรวจสอบแผนและข้อมูลก่อนอนุมัติการดำเนินการจริง" changes={["ตรวจ permission ของผู้ใช้งาน", "แสดงข้อมูลที่จะถูกสร้างหรือแก้ไข", "บันทึกผลการอนุมัติลง audit trail"]} onApprove={() => setOpen(false)} onReject={() => setOpen(false)} onClose={() => setOpen(false)} /></section></AIAccessGuard>;
}
