import { useState } from "react";
import { ArrowRight, Bot, CheckCircle2, ListTodo, Search, ShieldCheck, Sparkles } from "lucide-react";
import { AICommandBar } from "@/components/ai/AICommandBar";
import { AIAccessGuard } from "@/components/ai/AIAccessGuard";
import { Link } from "react-router-dom";

const quickActions = ["สร้างกิจกรรมจากเอกสาร", "ตรวจข้อมูลกิจกรรมที่ยังไม่ครบ", "สรุปผลกิจกรรมล่าสุด"];

function CommandCenterContent() {
  const [intent, setIntent] = useState("");
  return <section className="min-h-[calc(100vh-4rem)] bg-[#f8f9ff] px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]">
    <div className="rounded-2xl bg-[#002d62] px-5 py-6 text-white shadow-sm sm:px-7"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[10px] font-semibold tracking-wide text-[#d7e2ff]"><Sparkles className="h-3.5 w-3.5"/> AUTONOMOUS AI</div><h1 className="mt-3 text-2xl font-bold tracking-tight sm:text-[32px]">ศูนย์สั่งการอัจฉริยะ</h1><p className="mt-2 text-sm leading-6 text-[#d7e2ff]">บอกเป้าหมายเพียงครั้งเดียว แล้วให้ AI วางแผน จัดเตรียม และขออนุมัติเฉพาะขั้นตอนที่จำเป็น</p></div><div className="hidden rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-right sm:block"><p className="text-[10px] text-white/60">SYSTEM</p><p className="mt-1 text-xs font-semibold text-[#95f8a7]">READY</p></div></div><div className="mt-6 rounded-xl bg-[#00193c] p-2"><AICommandBar onSubmit={setIntent} placeholder="ค้นหาข้อมูล บริการ หรือบอก AI ว่าต้องการให้ทำอะไร…" /></div><div className="mt-3 flex flex-wrap gap-2">{quickActions.map((action) => <button key={action} type="button" onClick={() => setIntent(action)} className="rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-[11px] font-medium text-white/80 hover:bg-white/10">{action}</button>)}</div></div>
    {intent && <div className="mt-4 rounded-xl border border-[#c4c6d1] bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">CURRENT INTENT</p><p className="mt-1 text-sm font-semibold text-slate-900">{intent}</p><p className="mt-2 text-xs text-slate-500">คำสั่งถูกเก็บไว้ใน UI foundation เท่านั้น ยังไม่มี AI backend execution</p></div>}
    <div className="mt-5 grid gap-3 md:grid-cols-3">{[["/admin/ai/work-queue", ListTodo, "คิวงาน AI", "งานที่กำลังทำ รออนุมัติ หรือรอข้อมูล"],["/admin/ai/execution", Bot, "แผนและการทำงาน", "ดูขั้นตอน execution และผลการตรวจสอบ"],["/admin/ai/history", CheckCircle2, "ประวัติการทำงาน", "ตรวจสอบ execution ที่เกิดขึ้นจริง"]].map(([to, Icon, title, description]) => <Link key={String(to)} to={String(to)} className="group rounded-xl border border-[#c4c6d1] bg-white p-4 shadow-sm transition hover:border-[#3f5f8f] hover:shadow-md"><div className="flex items-center justify-between">{typeof Icon === "function" && <Icon className="h-5 w-5 text-[#002d62]"/>}<ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-[#002d62]"/></div><h2 className="mt-3 text-sm font-bold text-slate-900">{String(title)}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{String(description)}</p></Link>)}</div>
    <div className="mt-5 grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-xl border border-[#c4c6d1] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#eff4ff]"><Search className="h-4 w-4 text-[#002d62]"/></div><div><h2 className="text-sm font-bold text-slate-900">AI Workspace</h2><p className="text-xs text-slate-500">ทำงานจากข้อมูลจริงของ Portal โดยคงขอบเขตสิทธิ์เดิม</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[["INTENT","เข้าใจเป้าหมาย"],["PLAN","จัดลำดับงาน"],["APPROVAL","Admin ตัดสินใจ"]].map(([a,b]) => <div key={a} className="rounded-lg bg-[#f8f9ff] p-3"><p className="text-[10px] font-bold text-[#002d62]">{a}</p><p className="mt-1 text-xs text-slate-600">{b}</p></div>)}</div></div><div className="rounded-xl border border-[#95f8a7]/60 bg-[#effaf2] p-5"><ShieldCheck className="h-5 w-5 text-[#2e7d32]"/><h2 className="mt-2 text-sm font-bold text-[#003715]">Protected workspace</h2><p className="mt-1 text-xs leading-5 text-[#155d2b]">AI ใช้ AdminGuard, RBAC และ Portal API เป็นขอบเขตความปลอดภัย ไม่เขียนฐานข้อมูลโดยตรง</p></div></div>
  </div></section>;
}
export function AICommandCenterPage() { return <AIAccessGuard permission="ai.command.read"><CommandCenterContent /></AIAccessGuard>; }
