import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Filter, RefreshCw, Search } from "lucide-react";
import { getAdminDashboardData, type AdminDashboardData, type DashboardResponse } from "@/services/api";

type Period = "ALL" | "MONTH" | "QUARTER" | "YEAR" | "CUSTOM";
type ScoreField = keyof Pick<DashboardResponse, "p2_location" | "p2_schedule" | "p2_readiness" | "p2_reception" | "p2_overall" | "p3_interest" | "p3_content" | "p3_clarity" | "p3_benefit" | "p3_application" | "p4_knowledge" | "p4_inspiration" | "p4_community_resource" | "p4_future_return">;
const SCORE_FIELDS: ScoreField[] = ["p2_location", "p2_schedule", "p2_readiness", "p2_reception", "p2_overall", "p3_interest", "p3_content", "p3_clarity", "p3_benefit", "p3_application", "p4_knowledge", "p4_inspiration", "p4_community_resource", "p4_future_return"];
const TOPICS = [{ key: "event", label: "การจัดงาน", fields: SCORE_FIELDS.slice(0, 5) }, { key: "learning", label: "เนื้อหา / การเรียนรู้", fields: SCORE_FIELDS.slice(5, 10) }, { key: "impact", label: "ผลกระทบ", fields: SCORE_FIELDS.slice(10) }] as const;

function score(value: unknown) { const n = Number(value); return Number.isFinite(n) && n >= 1 && n <= 5 ? n : null; }
function formatDate(value?: string | null) { if (!value) return "-"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "-" : new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(date); }
function monthKey(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function inPeriod(value: string, period: Period, month: string, quarter: string, year: string, from: string, to: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return false; if (period === "ALL") return true; if (period === "YEAR") return String(date.getFullYear()) === year; if (period === "MONTH") return month ? monthKey(value) === month : true; if (period === "QUARTER") return `${date.getFullYear()}-Q${Math.floor(date.getMonth() / 3) + 1}` === quarter; return (!from || value.slice(0, 10) >= from) && (!to || value.slice(0, 10) <= to); }
function calculateSatisfaction(responses: DashboardResponse[]) { let sum = 0; let count = 0; for (const response of responses) for (const field of SCORE_FIELDS) { const value = score(response[field]); if (value !== null) { sum += value; count += 1; } } return { count, avg: count ? sum / count : null, percent: count ? (sum / (count * 5)) * 100 : null }; }

export function DashboardPage() {
  const [data, setData] = useState<AdminDashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [period, setPeriod] = useState<Period>("ALL");
  const [year, setYear] = useState("ALL");
  const [month, setMonth] = useState("");
  const [quarter, setQuarter] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [center, setCenter] = useState("ALL");
  const [organization, setOrganization] = useState("ALL");
  const [activity, setActivity] = useState("ALL");
  const [query, setQuery] = useState("");

  const load = async () => { setLoading(true); setError(""); try { setData(await getAdminDashboardData()); } catch (cause) { setError(cause instanceof Error ? cause.message : "ไม่สามารถโหลด Dashboard ได้"); } finally { setLoading(false); } };
  useEffect(() => { void load(); const refresh = () => void load(); window.addEventListener("dashboard:refresh", refresh); return () => window.removeEventListener("dashboard:refresh", refresh); }, []);

  const years = useMemo(() => [...new Set((data?.occurrences ?? []).map((item) => new Date(item.start_at).getFullYear()).filter(Number.isFinite))].sort((a, b) => b - a), [data]);
  const activeOccurrences = useMemo(() => (data?.occurrences ?? []).filter((item) => item.status !== "cancelled" && item.status !== "archived" && inPeriod(item.start_at, period, month, quarter, year === "ALL" ? "" : year, from, to)), [data, period, month, quarter, year, from, to]);
  const centerActivityIds = useMemo(() => new Set((data?.activityLearningCenters ?? []).filter((item) => center === "ALL" || item.learning_center_id === center).map((item) => item.activity_id)), [data, center]);
  const visibleActivities = useMemo(() => (data?.activities ?? []).filter((item) => activeOccurrences.some((occurrence) => occurrence.activity_id === item.id)).filter((item) => activity === "ALL" || item.id === activity).filter((item) => `${item.title} ${item.category ?? ""}`.toLowerCase().includes(query.toLowerCase())).filter((item) => center === "ALL" || centerActivityIds.has(item.id)), [data, activeOccurrences, activity, query, center, centerActivityIds]);
  const filteredActivityIds = useMemo(() => new Set(visibleActivities.map((item) => item.id)), [visibleActivities]);
  const filteredOccurrences = useMemo(() => activeOccurrences.filter((item) => filteredActivityIds.has(item.activity_id)), [activeOccurrences, filteredActivityIds]);
  const responseScope = useMemo(() => { const ids = new Set(filteredOccurrences.map((item) => item.id)); return (data?.responses ?? []).filter((response) => response.occurrence_id ? ids.has(response.occurrence_id) : filteredActivityIds.has(response.activity_id)).filter((response) => organization === "ALL" || response.participant_organization_id === organization); }, [data, filteredOccurrences, filteredActivityIds, organization]);
  const satisfaction = useMemo(() => calculateSatisfaction(responseScope), [responseScope]);
  const evaluatedActivities = useMemo(() => new Set(responseScope.map((item) => item.activity_id)).size, [responseScope]);
  const topicScores = useMemo(() => TOPICS.map((topic) => { const values: number[] = []; for (const response of responseScope) for (const field of topic.fields) { const value = score(response[field]); if (value !== null) values.push(value); } const avg = values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; return { ...topic, avg, percent: avg === null ? null : (avg / 5) * 100 }; }), [responseScope]);
  const photoActivities = useMemo(() => visibleActivities.filter((item) => Boolean(item.featured_image)).slice(0, 4), [visibleActivities]);
  const recentOccurrences = useMemo(() => [...filteredOccurrences].sort((a, b) => new Date(b.start_at).getTime() - new Date(a.start_at).getTime()).slice(0, 6), [filteredOccurrences]);
  const responseRate = useMemo(() => { const participants = filteredOccurrences.reduce((total, item) => total + Number(item.participant_count || 0), 0); return participants > 0 ? (responseScope.length / participants) * 100 : null; }, [filteredOccurrences, responseScope.length]);
  const reset = () => { setPeriod("ALL"); setYear("ALL"); setMonth(""); setQuarter(""); setFrom(""); setTo(""); setCenter("ALL"); setOrganization("ALL"); setActivity("ALL"); setQuery(""); };

  if (loading) return <div className="flex min-h-[60vh] items-center justify-center text-sm text-slate-500">กำลังโหลด Dashboard...</div>;
  if (error) return <div className="mx-auto max-w-3xl p-8"><div className="rounded-2xl border border-red-200 bg-red-50 p-6"><h1 className="text-lg font-bold text-red-800">ไม่สามารถโหลด Dashboard</h1><p className="mt-2 text-sm text-red-700">{error}</p><button onClick={() => void load()} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-navy px-4 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" />ลองใหม่</button></div></div>;

  return <div className="dashboard-screen bg-slate-50"><main className="mx-auto max-w-[1440px] space-y-3 px-4 py-3 sm:px-6 lg:px-8">
    <section className="dashboard-filter rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-brand-navy"><Filter className="h-3.5 w-3.5" />ตัวกรองข้อมูล</div><div className="flex flex-wrap items-center gap-2">
      <select value={period} onChange={(e) => setPeriod(e.target.value as Period)} className="dashboard-control"><option value="ALL">ทั้งหมด</option><option value="YEAR">รายปี</option><option value="QUARTER">รายไตรมาส</option><option value="MONTH">รายเดือน</option><option value="CUSTOM">กำหนดช่วงวันที่</option></select>
      {period === "YEAR" && <select value={year} onChange={(e) => setYear(e.target.value)} className="dashboard-control"><option value="ALL">ทุกปี</option>{years.map((item) => <option key={item} value={item}>{item + 543}</option>)}</select>}
      {period === "QUARTER" && <select value={quarter} onChange={(e) => setQuarter(e.target.value)} className="dashboard-control"><option value="">ทุกไตรมาส</option>{years.flatMap((item) => [1, 2, 3, 4].map((q) => <option key={`${item}-${q}`} value={`${item}-Q${q}`}>ไตรมาส {q}/{item + 543}</option>))}</select>}
      {period === "MONTH" && <input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="dashboard-control" />}
      {period === "CUSTOM" && <><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="dashboard-control" /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="dashboard-control" /></>}
      <select value={center} onChange={(e) => setCenter(e.target.value)} className="dashboard-control"><option value="ALL">ทุก Learning Center</option>{data?.learningCenters.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select value={organization} onChange={(e) => setOrganization(e.target.value)} className="dashboard-control"><option value="ALL">ทุกหน่วยงาน</option>{data?.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select value={activity} onChange={(e) => setActivity(e.target.value)} className="dashboard-control"><option value="ALL">ทุกกิจกรรม</option>{data?.activities.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>
      <div className="relative min-w-[180px] flex-1"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหากิจกรรม..." className="dashboard-control w-full pl-9" /></div>
      <button onClick={reset} className="min-h-9 rounded-xl border border-slate-200 px-3 text-xs font-semibold text-brand-navy hover:bg-slate-50">ล้างตัวกรอง</button>
    </div></section>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="กิจกรรมที่จัดจริง" value={filteredOccurrences.length.toLocaleString()} /><Kpi label="กิจกรรมที่มีผลประเมิน" value={evaluatedActivities.toLocaleString()} /><Kpi label="ผู้ตอบแบบสอบถาม" value={responseScope.length.toLocaleString()} /><Kpi label="คะแนนเฉลี่ย" value={satisfaction.avg === null ? "—" : `${satisfaction.avg.toFixed(2)} / 5`} /><Kpi label="ความพึงพอใจ" value={satisfaction.percent === null ? "—" : `${satisfaction.percent.toFixed(2)}%`} /></section>

    <section className="grid gap-3 lg:grid-cols-[1fr_1fr_1.15fr]"><Panel title="ความพึงพอใจรายด้าน" action="ดูรายละเอียด"><div className="space-y-3">{topicScores.map((item) => <div key={item.key}><div className="flex justify-between text-xs"><span className="font-medium text-slate-700">{item.label}</span><span className="font-semibold text-brand-navy">{item.avg === null ? "ไม่มีข้อมูล" : `${item.avg.toFixed(2)} / 5`}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${item.percent ?? 0}%` }} /></div></div>)}</div></Panel><Panel title="ผู้ตอบแบบประเมิน" subtitle="ตามหน่วยงาน"><RespondentChart organizations={data?.organizations ?? []} responses={responseScope} /></Panel><Panel title="ภาพกิจกรรม" subtitle="หลังเสร็จสิ้นกิจกรรม" action="ดูกิจกรรมทั้งหมด"><div className="grid grid-cols-2 gap-2">{photoActivities.map((item) => <div key={item.id} className="group overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative aspect-[4/3] overflow-hidden bg-slate-100"><img src={item.featured_image!} alt={`ภาพกิจกรรม ${item.title}`} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.03]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/80 to-transparent p-2 pt-6 text-white"><p className="truncate text-[11px] font-semibold">{item.title}</p></div></div></div>)}{photoActivities.length === 0 && <Empty text="ยังไม่มีภาพกิจกรรมหลังเสร็จสิ้นกิจกรรม" />}</div></Panel></section>

    <Panel title="กิจกรรมล่าสุด"><div className="overflow-hidden rounded-xl border border-slate-200"><table className="w-full text-left text-[11px]"><thead><tr className="bg-slate-50"><th className="p-2">วันที่</th><th className="p-2">กิจกรรม</th><th className="hidden p-2 md:table-cell">Learning Center</th><th className="p-2">สถานที่</th><th className="p-2 text-right">ผู้เข้าร่วม</th></tr></thead><tbody>{recentOccurrences.map((occurrence) => { const item = data?.activities.find((candidate) => candidate.id === occurrence.activity_id); const centerName = data?.learningCenters.find((centerItem) => data.activityLearningCenters.some((relation) => relation.learning_center_id === centerItem.id && relation.activity_id === occurrence.activity_id))?.name; return <tr key={occurrence.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="whitespace-nowrap p-2 text-slate-500">{formatDate(occurrence.start_at)}</td><td className="max-w-[320px] truncate p-2 font-semibold text-brand-navy">{item?.title ?? "กิจกรรม"}</td><td className="hidden p-2 text-slate-500 md:table-cell">{centerName ?? "-"}</td><td className="max-w-[180px] truncate p-2 text-slate-500">{occurrence.location_detail ?? occurrence.location_type ?? "-"}</td><td className="p-2 text-right font-semibold">{Number(occurrence.participant_count || 0).toLocaleString()}</td></tr>; })}</tbody></table>{recentOccurrences.length === 0 && <Empty text="ไม่มีกิจกรรมในเงื่อนไขที่เลือก" />}</div></Panel>

    <div className="flex items-center justify-end px-1 text-[10px] text-slate-400">Response Rate {responseRate === null ? "—" : `${responseRate.toFixed(1)}%`}</div>
  </main></div>;
}

function Panel({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: string; children: ReactNode }) { return <section className="dashboard-panel rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="mb-2 flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-brand-navy">{title}</h2>{subtitle && <p className="mt-0.5 text-[10px] text-slate-500">{subtitle}</p>}</div>{action && <button type="button" className="text-[10px] font-semibold text-brand-navy hover:underline">{action}</button>}</div>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="w-full rounded-xl border border-dashed border-slate-300 p-4 text-center text-xs text-slate-500">{text}</div>; }
function Kpi({ label, value }: { label: string; value: string }) { return <div className="dashboard-kpi rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-[11px] font-medium text-slate-500">{label}</p><p className="mt-0.5 text-2xl font-bold tracking-tight text-brand-navy">{value}</p></div>; }
function RespondentChart({ organizations, responses }: { organizations: { id: string; name: string }[]; responses: DashboardResponse[] }) { const counts = organizations.map((organization) => ({ ...organization, count: responses.filter((response) => response.participant_organization_id === organization.id).length })).filter((item) => item.count > 0).sort((a, b) => b.count - a.count).slice(0, 5); const total = counts.reduce((sum, item) => sum + item.count, 0); if (!total) return <Empty text="ยังไม่มีข้อมูลหน่วยงานของผู้ตอบ" />; return <div className="space-y-2">{counts.map((item) => <div key={item.id}><div className="flex justify-between gap-2 text-[11px]"><span className="truncate text-slate-600">{item.name}</span><span className="font-semibold text-brand-navy">{item.count.toLocaleString()} · {((item.count / total) * 100).toFixed(1)}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-navy" style={{ width: `${(item.count / total) * 100}%` }} /></div></div>)}</div>; }
