import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, BarChart3, CalendarDays, Filter, RefreshCw, Search, Users } from "lucide-react";
import { getAdminDashboardData, type AdminDashboardData, type DashboardResponse } from "@/services/api";

type Period = "ALL" | "MONTH" | "QUARTER" | "YEAR" | "CUSTOM";
type ScoreField = keyof Pick<DashboardResponse, "p2_location" | "p2_schedule" | "p2_readiness" | "p2_reception" | "p2_overall" | "p3_interest" | "p3_content" | "p3_clarity" | "p3_benefit" | "p3_application" | "p4_knowledge" | "p4_inspiration" | "p4_community_resource" | "p4_future_return">;
const SCORE_FIELDS: ScoreField[] = ["p2_location", "p2_schedule", "p2_readiness", "p2_reception", "p2_overall", "p3_interest", "p3_content", "p3_clarity", "p3_benefit", "p3_application", "p4_knowledge", "p4_inspiration", "p4_community_resource", "p4_future_return"];
const TOPICS = [{ key: "event", label: "การจัดงาน", fields: SCORE_FIELDS.slice(0, 5) }, { key: "learning", label: "เนื้อหา / การเรียนรู้", fields: SCORE_FIELDS.slice(5, 10) }, { key: "impact", label: "ผลกระทบ", fields: SCORE_FIELDS.slice(10) }] as const;

function score(value: unknown) { const n = Number(value); return Number.isFinite(n) && n >= 1 && n <= 5 ? n : null; }
function formatDate(value?: string | null) { if (!value) return "-"; const d = new Date(value); return Number.isNaN(d.getTime()) ? "-" : new Intl.DateTimeFormat("th-TH", { day: "2-digit", month: "short", year: "numeric" }).format(d); }
function monthKey(value: string) { const d = new Date(value); return Number.isNaN(d.getTime()) ? "" : `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`; }
function inPeriod(value: string, period: Period, month: string, quarter: string, year: string, from: string, to: string) { const d = new Date(value); if (Number.isNaN(d.getTime())) return false; if (period === "ALL") return true; if (period === "YEAR") return String(d.getFullYear()) === year; if (period === "MONTH") return month ? monthKey(value) === month : true; if (period === "QUARTER") return `${d.getFullYear()}-Q${Math.floor(d.getMonth() / 3) + 1}` === quarter; return (!from || value.slice(0, 10) >= from) && (!to || value.slice(0, 10) <= to); }
function calculateSatisfaction(responses: DashboardResponse[]) { let sum = 0, count = 0; for (const r of responses) for (const field of SCORE_FIELDS) { const n = score(r[field]); if (n !== null) { sum += n; count += 1; } } return { avg: count ? sum / count : null, percent: count ? (sum / (count * 5)) * 100 : null }; }

export function DashboardPage() {
  const [data, setData] = useState<AdminDashboardData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [period, setPeriod] = useState<Period>("ALL"); const [year, setYear] = useState("ALL"); const [month, setMonth] = useState(""); const [quarter, setQuarter] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [center, setCenter] = useState("ALL"); const [organization, setOrganization] = useState("ALL"); const [activity, setActivity] = useState("ALL"); const [query, setQuery] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setData(await getAdminDashboardData()); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถโหลด Dashboard ได้"); } finally { setLoading(false); } };
  useEffect(() => { void load(); const refresh = () => void load(); window.addEventListener("dashboard:refresh", refresh); return () => window.removeEventListener("dashboard:refresh", refresh); }, []);
  const years = useMemo(() => [...new Set((data?.occurrences ?? []).map((x) => new Date(x.start_at).getFullYear()).filter(Number.isFinite))].sort((a, b) => b - a), [data]);
  const occurrences = useMemo(() => (data?.occurrences ?? []).filter((x) => x.status !== "cancelled" && x.status !== "archived" && inPeriod(x.start_at, period, month, quarter, year === "ALL" ? "" : year, from, to)), [data, period, month, quarter, year, from, to]);
  const centerIds = useMemo(() => new Set((data?.activityLearningCenters ?? []).filter((x) => center === "ALL" || x.learning_center_id === center).map((x) => x.activity_id)), [data, center]);
  const activities = useMemo(() => (data?.activities ?? []).filter((x) => occurrences.some((o) => o.activity_id === x.id)).filter((x) => activity === "ALL" || x.id === activity).filter((x) => `${x.title} ${x.category ?? ""}`.toLowerCase().includes(query.toLowerCase())).filter((x) => center === "ALL" || centerIds.has(x.id)), [data, occurrences, activity, query, center, centerIds]);
  const activityIds = useMemo(() => new Set(activities.map((x) => x.id)), [activities]);
  const filteredOccurrences = useMemo(() => occurrences.filter((x) => activityIds.has(x.activity_id)), [occurrences, activityIds]);
  const responses = useMemo(() => { const ids = new Set(filteredOccurrences.map((x) => x.id)); return (data?.responses ?? []).filter((r) => r.occurrence_id ? ids.has(r.occurrence_id) : activityIds.has(r.activity_id)).filter((r) => organization === "ALL" || r.participant_organization_id === organization); }, [data, filteredOccurrences, activityIds, organization]);
  const satisfaction = useMemo(() => calculateSatisfaction(responses), [responses]);
  const evaluated = useMemo(() => new Set(responses.map((x) => x.activity_id)).size, [responses]);
  const topicScores = useMemo(() => TOPICS.map((topic) => { const values = topic.fields.flatMap((f) => responses.map((r) => score(r[f])).filter((x): x is number => x !== null)); const avg = values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; return { ...topic, avg, percent: avg === null ? null : (avg / 5) * 100 }; }), [responses]);
  const photos = useMemo(() => activities.filter((x) => x.featured_image).slice(0, 4), [activities]);
  const recent = useMemo(() => [...filteredOccurrences].sort((a, b) => new Date(b.start_at).getTime() - new Date(a.start_at).getTime()).slice(0, 5), [filteredOccurrences]);
  const reset = () => { setPeriod("ALL"); setYear("ALL"); setMonth(""); setQuarter(""); setFrom(""); setTo(""); setCenter("ALL"); setOrganization("ALL"); setActivity("ALL"); setQuery(""); };
  const participants = filteredOccurrences.reduce((sum, x) => sum + Number(x.participant_count || 0), 0); const responseRate = participants ? (responses.length / participants) * 100 : null;

  if (loading) return <div className="flex min-h-[70vh] items-center justify-center bg-[#f8f9ff] text-sm text-slate-500">กำลังโหลด Dashboard...</div>;
  if (error) return <div className="mx-auto max-w-3xl p-8"><div className="border border-red-200 bg-red-50 p-6"><h1 className="text-lg font-bold text-red-800">ไม่สามารถโหลด Dashboard</h1><p className="mt-2 text-sm text-red-700">{error}</p><button onClick={() => void load()} className="mt-4 inline-flex items-center gap-2 bg-[#002d62] px-4 py-2.5 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4"/>ลองใหม่</button></div></div>;

  return <div className="min-h-[calc(100vh-4rem)] bg-[#f8f9ff] text-[#0b1c30]"><main className="mx-auto max-w-[1440px] px-6 py-5 xl:px-8">
    <div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#3f5f8f]">CORE OVERVIEW</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-[#00193c]">ภาพรวมระบบ</h1><p className="mt-1 text-sm text-[#43474f]">ติดตามกิจกรรม ผลการประเมิน และผลลัพธ์จากการดำเนินงาน</p></div><div className="hidden items-center gap-2 text-xs text-[#43474f] sm:flex"><span className="h-2 w-2 rounded-full bg-[#2e7d32]"/>ข้อมูลพร้อมใช้งาน</div></div>

    <section className="mb-4 flex flex-wrap items-center gap-2 border-y border-[#dce9ff] bg-white px-3 py-2"><Filter className="h-4 w-4 text-[#3f5f8f]"/><select value={period} onChange={(e) => setPeriod(e.target.value as Period)} className="h-9 bg-[#eff4ff] px-3 text-xs font-semibold outline-none"><option value="ALL">ทุกช่วงเวลา</option><option value="YEAR">รายปี</option><option value="QUARTER">รายไตรมาส</option><option value="MONTH">รายเดือน</option><option value="CUSTOM">กำหนดช่วงวันที่</option></select>{period === "YEAR" && <select value={year} onChange={(e) => setYear(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"><option value="ALL">ทุกปี</option>{years.map((x) => <option key={x} value={x}>{x + 543}</option>)}</select>}{period === "QUARTER" && <select value={quarter} onChange={(e) => setQuarter(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"><option value="">ทุกไตรมาส</option>{years.flatMap((y) => [1,2,3,4].map((q) => <option key={`${y}-${q}`} value={`${y}-Q${q}`)}>ไตรมาส {q}/{y + 543}</option>))}</select>}{period === "MONTH" && <input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"/>}{period === "CUSTOM" && <><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"/><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"/></>}<select value={center} onChange={(e) => setCenter(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"><option value="ALL">ทุก Learning Center</option>{data?.learningCenters.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={organization} onChange={(e) => setOrganization(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"><option value="ALL">ทุกหน่วยงาน</option>{data?.organizations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={activity} onChange={(e) => setActivity(e.target.value)} className="h-9 bg-[#eff4ff] px-3 text-xs"><option value="ALL">ทุกกิจกรรม</option>{data?.activities.map((x) => <option key={x.id} value={x.id}>{x.title}</option>)}</select><div className="relative ml-auto min-w-[190px]"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหากิจกรรม..." className="h-9 w-full bg-[#eff4ff] pl-9 pr-3 text-xs outline-none focus:ring-1 focus:ring-[#002d62]"/></div><button onClick={reset} className="h-9 px-3 text-xs font-semibold text-[#002d62] hover:bg-[#eff4ff]">รีเซ็ต</button></section>

    <section className="mb-4 grid grid-cols-2 gap-px bg-[#c4c6d1] lg:grid-cols-5"><Metric icon={<Activity/>} label="กิจกรรมที่จัดจริง" value={filteredOccurrences.length.toLocaleString()}/><Metric icon={<BarChart3/>} label="กิจกรรมที่มีผลประเมิน" value={evaluated.toLocaleString()}/><Metric icon={<Users/>} label="ผู้ตอบแบบสอบถาม" value={responses.length.toLocaleString()}/><Metric label="คะแนนเฉลี่ย" value={satisfaction.avg === null ? "—" : satisfaction.avg.toFixed(2)} suffix="/ 5"/><Metric label="ความพึงพอใจ" value={satisfaction.percent === null ? "—" : `${satisfaction.percent.toFixed(2)}%`}/></section>

    <section className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr_1.25fr]"><Panel title="ความพึงพอใจรายด้าน" subtitle="Average score by topic"><div className="space-y-5">{topicScores.map((x) => <div key={x.key}><div className="mb-1 flex items-baseline justify-between"><span className="text-sm font-semibold text-[#0b1c30]">{x.label}</span><span className="text-sm font-semibold text-[#002d62]">{x.avg === null ? "—" : `${x.avg.toFixed(2)} / 5`}</span></div><div className="h-2 bg-[#dce9ff]"><div className="h-full bg-[#002d62]" style={{ width: `${x.percent ?? 0}%` }}/></div><div className="mt-1 text-[10px] text-[#747781]">{x.percent === null ? "ไม่มีข้อมูล" : `${x.percent.toFixed(1)}% ของคะแนนเต็ม`}</div></div>)}</div></Panel><Panel title="ผู้ตอบแบบประเมิน" subtitle="ตามหน่วยงาน"><RespondentChart organizations={data?.organizations ?? []} responses={responses}/><div className="mt-4 border-t border-[#dce9ff] pt-3 text-xs text-[#43474f]">Response rate <strong className="text-[#002d62]">{responseRate === null ? "—" : `${responseRate.toFixed(1)}%`}</strong></div></Panel><Panel title="ภาพกิจกรรม" subtitle="ภาพถ่ายหลังเสร็จสิ้นกิจกรรม"><div className="grid grid-cols-2 gap-2">{photos.map((x) => <figure key={x.id} className="group overflow-hidden bg-[#eff4ff]"><div className="aspect-[4/3] overflow-hidden"><img src={x.featured_image!} alt={`ภาพกิจกรรม ${x.title}`} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]"/></div><figcaption className="truncate border-t border-[#dce9ff] bg-white px-2 py-1.5 text-[11px] font-semibold text-[#0b1c30]">{x.title}</figcaption></figure>)}{!photos.length && <Empty text="ยังไม่มีภาพกิจกรรม"/>}</div></Panel></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><Panel title="กิจกรรมล่าสุด" subtitle="Recent activity operations"><div className="overflow-hidden border border-[#dce9ff] bg-white"><table className="w-full text-left text-xs"><thead className="bg-[#eff4ff] text-[10px] uppercase tracking-wide text-[#43474f]"><tr><th className="px-3 py-2.5">วันที่</th><th className="px-3 py-2.5">กิจกรรม</th><th className="hidden px-3 py-2.5 md:table-cell">สถานที่</th><th className="px-3 py-2.5 text-right">ผู้เข้าร่วม</th></tr></thead><tbody>{recent.map((o) => { const a = data?.activities.find((x) => x.id === o.activity_id); return <tr key={o.id} className="border-t border-[#dce9ff] hover:bg-[#f8f9ff]"><td className="whitespace-nowrap px-3 py-2.5 text-[#747781]">{formatDate(o.start_at)}</td><td className="max-w-[420px] truncate px-3 py-2.5 font-semibold text-[#00193c]">{a?.title ?? "กิจกรรม"}</td><td className="hidden max-w-[220px] truncate px-3 py-2.5 text-[#43474f] md:table-cell">{o.location_detail ?? o.location_type ?? "-"}</td><td className="px-3 py-2.5 text-right font-semibold">{Number(o.participant_count || 0).toLocaleString()}</td></tr>; })}</tbody></table>{!recent.length && <Empty text="ไม่มีกิจกรรมในเงื่อนไขที่เลือก"/>}</div></Panel><Panel title="สถานะการดำเนินงาน" subtitle="Operational snapshot"><div className="space-y-3"><Mini label="จัดกิจกรรม" value={filteredOccurrences.length}/><Mini label="ผู้เข้าร่วมตามแผน" value={participants}/><Mini label="ผู้ตอบประเมิน" value={responses.length}/><div className="border-t border-[#dce9ff] pt-3 text-xs text-[#747781] flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#3f5f8f]"/>ข้อมูลตามตัวกรองปัจจุบัน</div></div></Panel></section>
  </main></div>;
}

function Panel({ title, subtitle, children }: { title: string; subtitle?: string; children: ReactNode }) { return <section className="border border-[#dce9ff] bg-white p-4 shadow-[0_1px_8px_rgba(0,0,0,0.04)]"><div className="mb-4 border-b border-[#dce9ff] pb-3"><h2 className="text-base font-semibold text-[#00193c]">{title}</h2>{subtitle && <p className="mt-0.5 text-[11px] text-[#747781]">{subtitle}</p>}</div>{children}</section>; }
function Metric({ icon, label, value, suffix }: { icon?: ReactNode; label: string; value: string; suffix?: string }) { return <div className="bg-white px-4 py-3.5"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wide text-[#747781]">{icon && <span className="text-[#3f5f8f] [&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span>}{label}</div><div className="mt-1 text-[28px] font-bold leading-none tracking-tight text-[#00193c]">{value}<span className="ml-1 text-xs font-medium text-[#747781]">{suffix}</span></div></div>; }
function RespondentChart({ organizations, responses }: { organizations: { id: string; name: string }[]; responses: DashboardResponse[] }) { const items = organizations.map((o) => ({ ...o, count: responses.filter((r) => r.participant_organization_id === o.id).length })).filter((x) => x.count).sort((a, b) => b.count - a.count).slice(0, 5); const total = items.reduce((s, x) => s + x.count, 0); if (!total) return <Empty text="ยังไม่มีข้อมูลหน่วยงานของผู้ตอบ"/>; return <div className="space-y-3">{items.map((x) => <div key={x.id}><div className="flex justify-between text-xs"><span className="max-w-[180px] truncate text-[#43474f]">{x.name}</span><span className="font-semibold text-[#002d62]">{x.count.toLocaleString()} · {((x.count / total) * 100).toFixed(1)}%</span></div><div className="mt-1.5 h-2 bg-[#dce9ff]"><div className="h-full bg-[#3f5f8f]" style={{ width: `${(x.count / total) * 100}%` }}/></div></div>)}</div>; }
function Mini({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between border-b border-[#dce9ff] pb-2"><span className="text-xs text-[#43474f]">{label}</span><strong className="text-sm text-[#00193c]">{value.toLocaleString()}</strong></div>; }
function Empty({ text }: { text: string }) { return <div className="border border-dashed border-[#c4c6d1] px-4 py-6 text-center text-xs text-[#747781]">{text}</div>; }
