import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { apiRequest } from "@/services/api";

type Activity = {
  id: string; title: string; activityDate: string; status: string; featuredImage?: string | null;
  surveyEnabled: boolean; surveyOpenAt?: string | null; surveyCloseAt?: string | null;
  surveyWelcomeText?: string | null; responseCount: number;
};
type ResponseRow = Record<string, unknown> & { id: string; submitted_at: string };
const ratingFields = ["p2_location","p2_schedule","p2_readiness","p2_reception","p2_overall","p3_interest","p3_content","p3_clarity","p3_benefit","p3_application","p4_knowledge","p4_inspiration","p4_community_resource","p4_future_return"];
const csvCell = (v: unknown) => `"${String(v ?? "").replaceAll('"','""')}"`;

export function LacSatisfactionPage() {
  const [activities,setActivities]=useState<Activity[]>([]); const [selectedId,setSelectedId]=useState("");
  const [responses,setResponses]=useState<ResponseRow[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const selected=activities.find(a=>a.id===selectedId)??null;
  const [enabled,setEnabled]=useState(true); const [openAt,setOpenAt]=useState(""); const [closeAt,setCloseAt]=useState(""); const [welcome,setWelcome]=useState("");
  const load=async(activity="")=>{setLoading(true);try{const data=await apiRequest<{activities:Activity[];responses:ResponseRow[]}>(`/api/admin/lac-satisfaction${activity?`?activity=${encodeURIComponent(activity)}`:""}`);setActivities(data.activities??[]);setResponses(data.responses??[]);const current=data.activities.find(a=>a.id===(activity||selectedId))??data.activities[0];if(current){setSelectedId(current.id);setEnabled(current.surveyEnabled!==false);setOpenAt(current.surveyOpenAt?String(current.surveyOpenAt).slice(0,16):"");setCloseAt(current.surveyCloseAt?String(current.surveyCloseAt).slice(0,16):"");setWelcome(current.surveyWelcomeText??"");}}catch(e){toast.error(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]); useEffect(()=>{if(selectedId)void load(selectedId)},[selectedId]);
  const average=useMemo(()=>{const v=responses.flatMap(r=>ratingFields.map(k=>Number(r[k])).filter(n=>n>=1&&n<=5));return v.length?v.reduce((a,b)=>a+b,0)/v.length:0},[responses]);
  const save=async()=>{if(!selectedId)return;setSaving(true);try{await apiRequest(`/api/admin/lac-satisfaction?activity=${encodeURIComponent(selectedId)}`,{method:"PATCH",body:JSON.stringify({surveyEnabled:enabled,surveyOpenAt:openAt,surveyCloseAt:closeAt,surveyWelcomeText:welcome})});toast.success("บันทึกการตั้งค่าแบบประเมินแล้ว");await load(selectedId)}catch(e){toast.error(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const exportCsv=()=>{if(!responses.length){toast.error("ยังไม่มีข้อมูลสำหรับส่งออก");return}const headers=["id","submitted_at","age_group","affiliation","ever_joined","channels",...ratingFields,"feedback","pdpa_consent"];const csv=`\uFEFF${headers.map(csvCell).join(",")}\n${responses.map(r=>headers.map(h=>csvCell(r[h])).join(",")).join("\n")}`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`lac-satisfaction-${selected?.title??"activity"}.csv`;a.click()};
  return <main className="w-full max-w-7xl mx-auto p-4 md:p-8 space-y-6"><header><p className="text-sm font-semibold text-rose-700">Lac Learning Game</p><h1 className="text-3xl font-bold text-slate-900">ระบบประเมินความพึงพอใจ — Central Admin</h1><p className="mt-1 text-slate-500">ยืนยันสิทธิ์ที่ Portal Admin จุดเดียว แล้วจัดการกิจกรรม แบบประเมิน และข้อมูลผู้บริหารจากฐานกลาง</p></header>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="min-w-[280px] flex-1"><span className="mb-1 block text-xs font-semibold text-slate-500">กิจกรรม / ครั้ง</span><select className="w-full rounded-xl border px-3 py-2.5" value={selectedId} onChange={e=>setSelectedId(e.target.value)} disabled={loading}><option value="">เลือกกิจกรรม</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title} • {new Date(a.activityDate).toLocaleDateString("th-TH")}</option>)}</select></label><div className="rounded-xl bg-slate-50 px-5 py-3 text-sm"><b>{responses.length}</b> responses</div><div className="rounded-xl bg-slate-50 px-5 py-3 text-sm">คะแนนเฉลี่ย <b>{average.toFixed(2)} / 5</b></div><button onClick={exportCsv} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Export CSV</button></div></section>
  {selected&&<section className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm space-y-4"><div><h2 className="text-xl font-bold">ควบคุมแบบประเมิน</h2><p className="text-sm text-slate-500">{selected.title}</p></div><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span className="font-semibold">เปิดรับแบบประเมิน</span></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-semibold">เปิดรับตั้งแต่</span><input type="datetime-local" className="w-full rounded-xl border px-3 py-2" value={openAt} onChange={e=>setOpenAt(e.target.value)}/></label><label><span className="mb-1 block text-xs font-semibold">ปิดรับถึง</span><input type="datetime-local" className="w-full rounded-xl border px-3 py-2" value={closeAt} onChange={e=>setCloseAt(e.target.value)}/></label></div><label><span className="mb-1 block text-xs font-semibold">ข้อความต้อนรับ</span><textarea rows={4} className="w-full rounded-xl border px-3 py-2" value={welcome} onChange={e=>setWelcome(e.target.value)}/></label><button onClick={save} disabled={saving} className="w-full rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-50">{saving?"กำลังบันทึก...":"บันทึกการตั้งค่า"}</button></div>
  <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">ผลประเมินรายครั้ง</h2><p className="text-sm text-slate-500">ข้อมูลล่าสุดสูงสุด 5,000 รายการ</p></div><span className="rounded-full bg-rose-50 px-3 py-1 text-xs font-bold text-rose-700">Admin only</span></div><div className="max-h-[520px] overflow-auto rounded-xl border"><table className="w-full min-w-[760px] text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-2 text-left">เวลา</th><th className="p-2">สังกัด</th><th className="p-2">อายุ</th><th className="p-2">เฉลี่ย</th><th className="p-2 text-left">Feedback</th></tr></thead><tbody>{responses.map(r=>{const v=ratingFields.map(k=>Number(r[k])).filter(n=>n>=1&&n<=5);const avg=v.length?v.reduce((a,b)=>a+b,0)/v.length:0;return <tr key={r.id} className="border-t"><td className="p-2">{new Date(r.submitted_at).toLocaleString("th-TH")}</td><td className="p-2 text-center">{String(r.affiliation??"-")}</td><td className="p-2 text-center">{String(r.age_group??"-")}</td><td className="p-2 text-center font-bold">{avg.toFixed(2)}</td><td className="max-w-[280px] p-2">{String(r.feedback??"-")}</td></tr>})}{!responses.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-400">ยังไม่มีผลประเมินสำหรับกิจกรรมนี้</td></tr>}</tbody></table></div></div></section>}</main>;
}
