export const ADMIN_ROLES = [
  "SUPER_ADMIN",
  "CONTENT_ADMIN",
  "OPERATIONS_ADMIN",
  "FACILITY_ADMIN",
] as const;
export type AdminRole = (typeof ADMIN_ROLES)[number];
export const ADMIN_PERMISSIONS = [
  "overview.read",
  "cms.read",
  "cms.create",
  "cms.update",
  "cms.publish",
  "cms.archive",
  "activities.read",
  "activities.create",
  "activities.update",
  "activities.publish",
  "activities.archive",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.publish",
  "projects.archive",
  "learning_centers.read",
  "learning_centers.create",
  "learning_centers.update",
  "learning_centers.publish",
  "learning_centers.archive",
  "partners.read",
  "partners.create",
  "partners.update",
  "partners.archive",
  "services.read",
  "services.create",
  "services.update",
  "services.publish",
  "services.archive",
  "navigation.read",
  "navigation.create",
  "navigation.update",
  "navigation.archive",
  "footer.read",
  "footer.update",
  "facility.read",
  "facility.manage",
  "store.read",
  "store.manage",
  "system.read",
  "system.manage",
  "survey.read",
  "survey.create",
  "survey.update",
  "survey.archive",
  "survey.audit.read",
  "ai.command.read",
  "ai.queue.read",
  "ai.execution.read",
  "ai.approval.read",
] as const;
export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];

const CONTENT: readonly AdminPermission[] = [
  "overview.read",
  "cms.read",
  "cms.create",
  "cms.update",
  "cms.publish",
  "cms.archive",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.publish",
  "projects.archive",
  "partners.read",
  "partners.create",
  "partners.update",
  "partners.archive",
  "services.read",
  "services.create",
  "services.update",
  "services.publish",
  "services.archive",
  "navigation.read",
  "navigation.create",
  "navigation.update",
  "navigation.archive",
  "footer.read",
  "footer.update",
  "survey.read",
  "survey.create",
  "survey.update",
  "survey.archive",
  "survey.audit.read",
  "ai.command.read",
  "ai.queue.read",
  "ai.execution.read",
  "ai.approval.read",
];
const OPERATIONS: readonly AdminPermission[] = [
  "overview.read",
  "activities.read",
  "activities.create",
  "activities.update",
  "activities.publish",
  "activities.archive",
  "learning_centers.read",
  "learning_centers.create",
  "learning_centers.update",
  "learning_centers.publish",
  "learning_centers.archive",
  "store.read",
  "store.manage",
  "survey.read",
  "survey.create",
  "survey.update",
  "survey.archive",
  "survey.audit.read",
  "ai.command.read",
  "ai.queue.read",
  "ai.execution.read",
  "ai.approval.read",
];
const FACILITY: readonly AdminPermission[] = [
  "overview.read",
  "facility.read",
  "facility.manage",
  "survey.read",
  "survey.audit.read",
  "ai.command.read",
  "ai.queue.read",
  "ai.execution.read",
  "ai.approval.read",
];
const ROLE_PERMISSIONS: Record<AdminRole, readonly AdminPermission[]> = {
  SUPER_ADMIN: ADMIN_PERMISSIONS,
  CONTENT_ADMIN: CONTENT,
  OPERATIONS_ADMIN: OPERATIONS,
  FACILITY_ADMIN: FACILITY,
};

export function isAdminRole(value: unknown): value is AdminRole {
  return typeof value === "string" && (ADMIN_ROLES as readonly string[]).includes(value);
}
export function hasAdminPermission(
  role: AdminRole | null | undefined,
  permission: string,
): boolean {
  return (
    role === "SUPER_ADMIN" ||
    Boolean(role && ROLE_PERMISSIONS[role].includes(permission as AdminPermission))
  );
}
export function permissionsForRole(role: AdminRole | null | undefined): AdminPermission[] {
  return role ? [...ROLE_PERMISSIONS[role]] : [];
}
